### PR TITLE
Update README.md with link to Mercedes' Winter Freeze Thaw Analysis of COSORE

### PR DESCRIPTION
**Pull request by mlkhorn**
In this commit I add a link to the repository for my winter time and freeze thaw period analysis of data in COSORE to the README.md file of the SULI 2020 repository.

### CODE REVIEW

**Comment by bpbond** [comment]
Thanks! @skygering can you wait until #14 is merged, and then review and merge this (dealing with any Git conflict bwahahaha that might show up).

**Comment by bpbond** [comment]
Oh no a conflict! 😉  Over to you @skygering

**Comment by skygering** [comment]
@bpbond  should Mercedes' branch be deleted? Also, I did this using the web UI because I was kind of confused on how to do it locally. If I wanted to do it locally would I pull the master branch or Mercedes' branch to merge?

**Comment by bpbond** [comment]
@skygering Yes, delete the branch. Mercedes will still have the branch on her local machine if she wants to do more work on it.

Web UI is a great place to start with merge conflict in many cases. To do it locally, you'd pull Mercedes' branch, merge in `master`, resolve and conflicts, and push.

Thanks!

**Pull request merged**
